name = "DeviceDefinitions"
uuid = "beead57b-6593-4141-bbb8-edf896229b7f"
authors = ["Sukera <Seelengrab@users.noreply.github.com>"]
version = "0.1.5"

[deps]
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MCUCommon = "455ac959-662e-47bc-a1c5-e582af05f21d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"

[compat]
EnumX = "1"
Logging = "1.6"
MCUCommon = "0.1.5"
Pkg = "1.6"
XML = "0.3.1"
julia = "1.6"
